# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detectify.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from run_model import run_dicom_through_model, get_transformed_dicom_as_array
import os
import matplotlib.pyplot as plt
import queue 
from PIL import Image, ImageEnhance
import cv2
import numpy as np

class DataResultObj(QtCore.QObject):
    def __init__(self, data):
        self.data = data

class DataProcessingThread(QtCore.QThread):
    result_ready = QtCore.pyqtSignal(object)

    def __init__(self, queue, callback):
        super().__init__()
        self.queue = queue
        self.result_ready.connect(callback)
        self.filename = None

    def run(self):
        data = get_transformed_dicom_as_array(self.filename)
        self.result_ready.emit(DataResultObj(data))

    def setFilename(self, filename):
        self.filename = filename

class AIProcessingThread(QtCore.QThread):
    result_ready = QtCore.pyqtSignal(object)

    def __init__(self, queue, callback):
        self.filename = None
        self.queue = queue
        self.callback = callback

    def run(self):
        data = run_dicom_through_model(self.filename)
        self.result_ready.emit(DataResultObj(data))

    def set_filename(self, filename):
        self.filename = filename
        

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 71, 521))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalSlider = QtWidgets.QSlider(self.horizontalLayoutWidget) ## slicer
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.horizontalLayout.addWidget(self.verticalSlider)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 58, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 550, 58, 18))
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(480, 550, 171, 22))
        self.checkBox.setObjectName("checkBox")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(80, 0, 61, 51))
        self.toolButton.setObjectName("toolButton")
        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setGeometry(QtCore.QRect(660, 60, 20, 160)) ## contrast
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.verticalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_3.setGeometry(QtCore.QRect(660, 250, 20, 160)) ## brightness
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.toolButton_6 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_6.setGeometry(QtCore.QRect(290, 0, 61, 51))
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_7 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_7.setGeometry(QtCore.QRect(590, 0, 61, 51))
        self.toolButton_7.setObjectName("toolButton_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 250, 58, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(680, 390, 58, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 60, 58, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(680, 200, 58, 18))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 80, 551, 441))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.queue = queue.Queue()
        self.aiqueue = queue.Queue()
        self.data_thread = DataProcessingThread(self.queue, self.handleThreadResult)
        self.data_thread.result_ready.connect(self.projectInitialDICOM)


        self.aithread = AIProcessingThread(self.aiqueue, self.handleAIResult)

        self.data_array = None
        self.ai_data_array = None
        self.data_slice_nums = None
        self.masked_data = None
        self.fileName = None
        self.pixmap = None
        self.rotation = 0
        self.brightness = 1
        self.contrast = 1
        self.scale = 1

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Max Slice"))
        self.label_2.setText(_translate("MainWindow", "Min Slice"))

        self.checkBox.setText(_translate("MainWindow", "Segmentation Enabled"))
        self.checkBox.toggled.connect(self.changeSegmentation)

        self.verticalSlider.valueChanged[int].connect(self.sliceData)
        self.verticalSlider.setMinimum(0)
        self.verticalSlider.setMaximum(100)


        self.verticalSlider_2.valueChanged[int].connect(self.adjustData)
        self.verticalSlider_2.setMinimum(0)
        self.verticalSlider_2.setMaximum(200)
        self.verticalSlider_2.setValue(100)
        self.verticalSlider_3.valueChanged[int].connect(self.adjustData)
        self.verticalSlider_3.setMinimum(0)
        self.verticalSlider_3.setMaximum(200)
        self.verticalSlider_3.setValue(100)

        self.toolButton.setText(_translate("MainWindow", "File"))
        self.toolButton.clicked.connect(self.filebuttonClicked)

        self.toolButton_6.setText(_translate("MainWindow", "Rotate+90"))
        self.toolButton_6.clicked.connect(self.rotateButtonClicked)

        self.toolButton_7.setText(_translate("MainWindow", "Process"))
        self.toolButton_7.clicked.connect(self.processbuttonClicked)
        self.label_3.setText(_translate("MainWindow", "B+"))
        self.label_4.setText(_translate("MainWindow", "B-"))
        self.label_5.setText(_translate("MainWindow", "C+"))
        self.label_6.setText(_translate("MainWindow", "C-"))

    def handleThreadResult(self, dataobject):
        data = dataobject.data
        self.data_array = data
        self.data_slice_nums = self.data_array.shape[-1]

    def adjustData(self):
        alpha = self.verticalSlider_3.value() / 100
        beta = self.verticalSlider_2.value() / 100

        if self.checkBox.checkState() == QtCore.Qt.CheckState.Checked:
            image = Image.open(f"temp/temp{self.verticalSlider.value()}.jpeg")
            img_enhancer = ImageEnhance.Brightness(image)
            enhanced_output = img_enhancer.enhance(alpha)

            img_enhancer_contrast = ImageEnhance.Contrast(enhanced_output)
            enhanced_output = img_enhancer_contrast.enhance(beta)
            
            enhanced_output.save(f"temp/temp{self.verticalSlider.value()}_adjusted.jpeg")

            self.refreshGraphics(True, "_adjusted")
        else:
            image = Image.open("temp/temp.jpeg")
            img_enhancer = ImageEnhance.Brightness(image)
            enhanced_output = img_enhancer.enhance(alpha)
            img_enhancer_contrast = ImageEnhance.Contrast(enhanced_output)
            enhanced_output = img_enhancer_contrast.enhance(beta)

            enhanced_output.save("temp/temp_adjusted.jpeg")

            self.refreshGraphics(False, "_adjusted")

    def handleAIResult(self, dataobject):
        self.ai_data_array = dataobject.data

    def refreshGraphics(self, is_ai, additional=""):
        if is_ai:
            self.label_7.setPixmap(QtGui.QPixmap(f"temp/temp{self.verticalSlider.value()}{additional}.jpeg"))
            self.pixmap = QtGui.QPixmap(f"temp/temp{self.verticalSlider.value()}{additional}.jpeg")
        else:
            self.label_7.setPixmap(QtGui.QPixmap(f"temp/temp{additional}.jpeg"))
            self.pixmap = QtGui.QPixmap(f"temp/temp{additional}.jpeg")

        self.label_7.setScaledContents(True)

    def rotateButtonClicked(self):
        self.rotation += 90
        if self.checkBox.checkState() == QtCore.Qt.CheckState.Checked:
            temp_image = Image.open(f"temp/temp{self.verticalSlider.value()}.jpeg")
            rotated_image = temp_image.rotate(self.rotation)
            rotated_image.save(f"temp/temp{self.verticalSlider.value()}_rotated.jpeg")
            self.refreshGraphics(True, "_rotated")
        else:
            temp_image = Image.open("temp/temp.jpeg")
            rotated_image = temp_image.rotate(self.rotation)
            rotated_image.save("temp/temp_rotated.jpeg")
            self.refreshGraphics(False, "_rotated")

    def sliceData(self, value):
        if self.data_array is not None and (self.checkBox.checkState() != QtCore.Qt.CheckState.Checked):
            plt.imsave("temp/temp.jpeg", self.data_array[0, 0, :, :, self.verticalSlider.value()], cmap="gray")
            self.refreshGraphics(False)

        if self.checkBox.checkState() == QtCore.Qt.CheckState.Checked:
            self.refreshGraphics(True)

    def on_zoom_out(self, event):
        self.scale /= 2
        self.resize_image()

    def on_zoom_in(self, event):
        self.scale *= 2
        self.resize_image()

    def resize_image(self):
        size = self.pixmap.size()
        scaled_pixmap = self.pixmap.scaled(self.scale * size)
        self.label_7.setPixmap(scaled_pixmap)

    def processbuttonClicked(self):
        if self.data_array is not None:
            data = run_dicom_through_model(self.filename)
            self.ai_data_array = data
            
            for i in range(0, self.data_slice_nums):
                plt.axis('off')
                plt.imshow(self.data_array[0, 0, :, :, i], cmap="gray")
                plt.imshow(self.ai_data_array[0, :, :, i], cmap='jet', alpha=0.5)
                plt.savefig(f"temp/temp{i}.jpeg", bbox_inches='tight', pad_inches=0)

    def changeSegmentation(self):
        if self.data_array is not None and self.checkBox.checkState() == QtCore.Qt.CheckState.Checked:
            #plt.imsave("temp/temp.jpeg", self.ai_data_array[0, :, :, self.verticalSlider.value()], cmap='jet')
            self.refreshGraphics(True)

        if self.data_array is not None and self.checkBox.checkState() != QtCore.Qt.CheckState.Checked:
            plt.imsave("temp/temp.jpeg", self.data_array[0, 0, :, :, self.verticalSlider.value()], cmap="gray")

            self.refreshGraphics(False)

    def filebuttonClicked(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(None, "Choose File", "", "DICOM (*.gz)", options=options)

        if fileName:
            print(fileName)
            self.filename = fileName
            self.data_thread.setFilename(fileName)
            self.data_thread.start()

    def projectInitialDICOM(self, data):
        if self.data_array is not None and self.data_slice_nums is not None:
            self.verticalSlider.setMaximum(self.data_slice_nums-1)

            plt.imsave("temp/temp.jpeg", self.data_array[0, 0, :, :, 0], cmap="gray")
            self.refreshGraphics(False)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
